// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPools implements IPPoolInterface
type fakeIPPools struct {
	*gentype.FakeClientWithListAndApply[*v1.IPPool, *v1.IPPoolList, *kubeovnv1.IPPoolApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeIPPools(fake *FakeKubeovnV1) typedkubeovnv1.IPPoolInterface {
	return &fakeIPPools{
		gentype.NewFakeClientWithListAndApply[*v1.IPPool, *v1.IPPoolList, *kubeovnv1.IPPoolApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("ippools"),
			v1.SchemeGroupVersion.WithKind("IPPool"),
			func() *v1.IPPool { return &v1.IPPool{} },
			func() *v1.IPPoolList { return &v1.IPPoolList{} },
			func(dst, src *v1.IPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IPPoolList) []*v1.IPPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.IPPoolList, items []*v1.IPPool) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
