// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeQoSPolicies implements QoSPolicyInterface
type fakeQoSPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1.QoSPolicy, *v1.QoSPolicyList, *kubeovnv1.QoSPolicyApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeQoSPolicies(fake *FakeKubeovnV1) typedkubeovnv1.QoSPolicyInterface {
	return &fakeQoSPolicies{
		gentype.NewFakeClientWithListAndApply[*v1.QoSPolicy, *v1.QoSPolicyList, *kubeovnv1.QoSPolicyApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("qos-policies"),
			v1.SchemeGroupVersion.WithKind("QoSPolicy"),
			func() *v1.QoSPolicy { return &v1.QoSPolicy{} },
			func() *v1.QoSPolicyList { return &v1.QoSPolicyList{} },
			func(dst, src *v1.QoSPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.QoSPolicyList) []*v1.QoSPolicy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.QoSPolicyList, items []*v1.QoSPolicy) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
