// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeovnV1 struct {
	*testing.Fake
}

func (c *FakeKubeovnV1) IPs() v1.IPInterface {
	return &FakeIPs{c}
}

func (c *FakeKubeovnV1) IPPools() v1.IPPoolInterface {
	return &FakeIPPools{c}
}

func (c *FakeKubeovnV1) IptablesDnatRules() v1.IptablesDnatRuleInterface {
	return &FakeIptablesDnatRules{c}
}

func (c *FakeKubeovnV1) IptablesEIPs() v1.IptablesEIPInterface {
	return &FakeIptablesEIPs{c}
}

func (c *FakeKubeovnV1) IptablesFIPRules() v1.IptablesFIPRuleInterface {
	return &FakeIptablesFIPRules{c}
}

func (c *FakeKubeovnV1) IptablesSnatRules() v1.IptablesSnatRuleInterface {
	return &FakeIptablesSnatRules{c}
}

func (c *FakeKubeovnV1) OvnDnatRules() v1.OvnDnatRuleInterface {
	return &FakeOvnDnatRules{c}
}

func (c *FakeKubeovnV1) OvnEips() v1.OvnEipInterface {
	return &FakeOvnEips{c}
}

func (c *FakeKubeovnV1) OvnFips() v1.OvnFipInterface {
	return &FakeOvnFips{c}
}

func (c *FakeKubeovnV1) OvnSnatRules() v1.OvnSnatRuleInterface {
	return &FakeOvnSnatRules{c}
}

func (c *FakeKubeovnV1) ProviderNetworks() v1.ProviderNetworkInterface {
	return &FakeProviderNetworks{c}
}

func (c *FakeKubeovnV1) QoSPolicies() v1.QoSPolicyInterface {
	return &FakeQoSPolicies{c}
}

func (c *FakeKubeovnV1) SecurityGroups() v1.SecurityGroupInterface {
	return &FakeSecurityGroups{c}
}

func (c *FakeKubeovnV1) Subnets() v1.SubnetInterface {
	return &FakeSubnets{c}
}

func (c *FakeKubeovnV1) SwitchLBRules() v1.SwitchLBRuleInterface {
	return &FakeSwitchLBRules{c}
}

func (c *FakeKubeovnV1) Vips() v1.VipInterface {
	return &FakeVips{c}
}

func (c *FakeKubeovnV1) Vlans() v1.VlanInterface {
	return &FakeVlans{c}
}

func (c *FakeKubeovnV1) Vpcs() v1.VpcInterface {
	return &FakeVpcs{c}
}

func (c *FakeKubeovnV1) VpcDnses() v1.VpcDnsInterface {
	return &FakeVpcDnses{c}
}

func (c *FakeKubeovnV1) VpcNatGateways() v1.VpcNatGatewayInterface {
	return &FakeVpcNatGateways{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeovnV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
