// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPs implements IPInterface
type fakeIPs struct {
	*gentype.FakeClientWithListAndApply[*v1.IP, *v1.IPList, *kubeovnv1.IPApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeIPs(fake *FakeKubeovnV1) typedkubeovnv1.IPInterface {
	return &fakeIPs{
		gentype.NewFakeClientWithListAndApply[*v1.IP, *v1.IPList, *kubeovnv1.IPApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("ips"),
			v1.SchemeGroupVersion.WithKind("IP"),
			func() *v1.IP { return &v1.IP{} },
			func() *v1.IPList { return &v1.IPList{} },
			func(dst, src *v1.IPList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IPList) []*v1.IP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.IPList, items []*v1.IP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
