// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVips implements VipInterface
type fakeVips struct {
	*gentype.FakeClientWithListAndApply[*v1.Vip, *v1.VipList, *kubeovnv1.VipApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeVips(fake *FakeKubeovnV1) typedkubeovnv1.VipInterface {
	return &fakeVips{
		gentype.NewFakeClientWithListAndApply[*v1.Vip, *v1.VipList, *kubeovnv1.VipApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("vips"),
			v1.SchemeGroupVersion.WithKind("Vip"),
			func() *v1.Vip { return &v1.Vip{} },
			func() *v1.VipList { return &v1.VipList{} },
			func(dst, src *v1.VipList) { dst.ListMeta = src.ListMeta },
			func(list *v1.VipList) []*v1.Vip { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.VipList, items []*v1.Vip) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
