// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeOvnEips implements OvnEipInterface
type fakeOvnEips struct {
	*gentype.FakeClientWithListAndApply[*v1.OvnEip, *v1.OvnEipList, *kubeovnv1.OvnEipApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeOvnEips(fake *FakeKubeovnV1) typedkubeovnv1.OvnEipInterface {
	return &fakeOvnEips{
		gentype.NewFakeClientWithListAndApply[*v1.OvnEip, *v1.OvnEipList, *kubeovnv1.OvnEipApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("ovn-eips"),
			v1.SchemeGroupVersion.WithKind("OvnEip"),
			func() *v1.OvnEip { return &v1.OvnEip{} },
			func() *v1.OvnEipList { return &v1.OvnEipList{} },
			func(dst, src *v1.OvnEipList) { dst.ListMeta = src.ListMeta },
			func(list *v1.OvnEipList) []*v1.OvnEip { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.OvnEipList, items []*v1.OvnEip) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
