// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	typedkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVpcDnses implements VpcDnsInterface
type fakeVpcDnses struct {
	*gentype.FakeClientWithListAndApply[*v1.VpcDns, *v1.VpcDnsList, *kubeovnv1.VpcDnsApplyConfiguration]
	Fake *FakeKubeovnV1
}

func newFakeVpcDnses(fake *FakeKubeovnV1) typedkubeovnv1.VpcDnsInterface {
	return &fakeVpcDnses{
		gentype.NewFakeClientWithListAndApply[*v1.VpcDns, *v1.VpcDnsList, *kubeovnv1.VpcDnsApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("vpc-dnses"),
			v1.SchemeGroupVersion.WithKind("VpcDns"),
			func() *v1.VpcDns { return &v1.VpcDns{} },
			func() *v1.VpcDnsList { return &v1.VpcDnsList{} },
			func(dst, src *v1.VpcDnsList) { dst.ListMeta = src.ListMeta },
			func(list *v1.VpcDnsList) []*v1.VpcDns { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.VpcDnsList, items []*v1.VpcDns) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
