// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"
	json "encoding/json"
	fmt "fmt"

	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVlans implements VlanInterface
type FakeVlans struct {
	Fake *FakeKubeovnV1
}

var vlansResource = v1.SchemeGroupVersion.WithResource("vlans")

var vlansKind = v1.SchemeGroupVersion.WithKind("Vlan")

// Get takes name of the vlan, and returns the corresponding vlan object, and an error if there is any.
func (c *FakeVlans) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Vlan, err error) {
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(vlansResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// List takes label and field selectors, and returns the list of Vlans that match those selectors.
func (c *FakeVlans) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VlanList, err error) {
	emptyResult := &v1.VlanList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(vlansResource, vlansKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.VlanList{ListMeta: obj.(*v1.VlanList).ListMeta}
	for _, item := range obj.(*v1.VlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vlans.
func (c *FakeVlans) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(vlansResource, opts))
}

// Create takes the representation of a vlan and creates it.  Returns the server's representation of the vlan, and an error, if there is any.
func (c *FakeVlans) Create(ctx context.Context, vlan *v1.Vlan, opts metav1.CreateOptions) (result *v1.Vlan, err error) {
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(vlansResource, vlan, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// Update takes the representation of a vlan and updates it. Returns the server's representation of the vlan, and an error, if there is any.
func (c *FakeVlans) Update(ctx context.Context, vlan *v1.Vlan, opts metav1.UpdateOptions) (result *v1.Vlan, err error) {
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(vlansResource, vlan, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVlans) UpdateStatus(ctx context.Context, vlan *v1.Vlan, opts metav1.UpdateOptions) (result *v1.Vlan, err error) {
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(vlansResource, "status", vlan, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// Delete takes name of the vlan and deletes it. Returns an error if one occurs.
func (c *FakeVlans) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(vlansResource, name, opts), &v1.Vlan{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVlans) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(vlansResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.VlanList{})
	return err
}

// Patch applies the patch and returns the patched vlan.
func (c *FakeVlans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Vlan, err error) {
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vlansResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied vlan.
func (c *FakeVlans) Apply(ctx context.Context, vlan *kubeovnv1.VlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vlan, err error) {
	if vlan == nil {
		return nil, fmt.Errorf("vlan provided to Apply must not be nil")
	}
	data, err := json.Marshal(vlan)
	if err != nil {
		return nil, err
	}
	name := vlan.Name
	if name == nil {
		return nil, fmt.Errorf("vlan.Name must be provided to Apply")
	}
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vlansResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeVlans) ApplyStatus(ctx context.Context, vlan *kubeovnv1.VlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vlan, err error) {
	if vlan == nil {
		return nil, fmt.Errorf("vlan provided to Apply must not be nil")
	}
	data, err := json.Marshal(vlan)
	if err != nil {
		return nil, err
	}
	name := vlan.Name
	if name == nil {
		return nil, fmt.Errorf("vlan.Name must be provided to Apply")
	}
	emptyResult := &v1.Vlan{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(vlansResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vlan), err
}
