// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"
	json "encoding/json"
	fmt "fmt"

	v1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQoSPolicies implements QoSPolicyInterface
type FakeQoSPolicies struct {
	Fake *FakeKubeovnV1
}

var qospoliciesResource = v1.SchemeGroupVersion.WithResource("qos-policies")

var qospoliciesKind = v1.SchemeGroupVersion.WithKind("QoSPolicy")

// Get takes name of the qoSPolicy, and returns the corresponding qoSPolicy object, and an error if there is any.
func (c *FakeQoSPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.QoSPolicy, err error) {
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(qospoliciesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// List takes label and field selectors, and returns the list of QoSPolicies that match those selectors.
func (c *FakeQoSPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.QoSPolicyList, err error) {
	emptyResult := &v1.QoSPolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(qospoliciesResource, qospoliciesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.QoSPolicyList{ListMeta: obj.(*v1.QoSPolicyList).ListMeta}
	for _, item := range obj.(*v1.QoSPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested qoSPolicies.
func (c *FakeQoSPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(qospoliciesResource, opts))
}

// Create takes the representation of a qoSPolicy and creates it.  Returns the server's representation of the qoSPolicy, and an error, if there is any.
func (c *FakeQoSPolicies) Create(ctx context.Context, qoSPolicy *v1.QoSPolicy, opts metav1.CreateOptions) (result *v1.QoSPolicy, err error) {
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(qospoliciesResource, qoSPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// Update takes the representation of a qoSPolicy and updates it. Returns the server's representation of the qoSPolicy, and an error, if there is any.
func (c *FakeQoSPolicies) Update(ctx context.Context, qoSPolicy *v1.QoSPolicy, opts metav1.UpdateOptions) (result *v1.QoSPolicy, err error) {
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(qospoliciesResource, qoSPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQoSPolicies) UpdateStatus(ctx context.Context, qoSPolicy *v1.QoSPolicy, opts metav1.UpdateOptions) (result *v1.QoSPolicy, err error) {
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(qospoliciesResource, "status", qoSPolicy, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// Delete takes name of the qoSPolicy and deletes it. Returns an error if one occurs.
func (c *FakeQoSPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(qospoliciesResource, name, opts), &v1.QoSPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQoSPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(qospoliciesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.QoSPolicyList{})
	return err
}

// Patch applies the patch and returns the patched qoSPolicy.
func (c *FakeQoSPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.QoSPolicy, err error) {
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(qospoliciesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied qoSPolicy.
func (c *FakeQoSPolicies) Apply(ctx context.Context, qoSPolicy *kubeovnv1.QoSPolicyApplyConfiguration, opts metav1.ApplyOptions) (result *v1.QoSPolicy, err error) {
	if qoSPolicy == nil {
		return nil, fmt.Errorf("qoSPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(qoSPolicy)
	if err != nil {
		return nil, err
	}
	name := qoSPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("qoSPolicy.Name must be provided to Apply")
	}
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(qospoliciesResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeQoSPolicies) ApplyStatus(ctx context.Context, qoSPolicy *kubeovnv1.QoSPolicyApplyConfiguration, opts metav1.ApplyOptions) (result *v1.QoSPolicy, err error) {
	if qoSPolicy == nil {
		return nil, fmt.Errorf("qoSPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(qoSPolicy)
	if err != nil {
		return nil, err
	}
	name := qoSPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("qoSPolicy.Name must be provided to Apply")
	}
	emptyResult := &v1.QoSPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(qospoliciesResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.QoSPolicy), err
}
