// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: kubevim-admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Admin_DownloadImage_FullMethodName         = "/admin.kubevim.kubenfv.api.pb.admin/DownloadImage"
	Admin_SetupImageUploadProxy_FullMethodName = "/admin.kubevim.kubenfv.api.pb.admin/SetupImageUploadProxy"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	// Software Image Management Interface
	//
	// This operation allows downloading and initializing a software image from
	// the specified image repository.
	// Result: As a result of this operation, the requested software image should be present
	// and available for querying via the ETSI NFV IFA-006 Vi-Vnfm API.
	DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (*DownloadImageResponse, error)
	// This operation sets up the software image upload proxy, which can be used for
	// software image uploading from external services.
	// Result: As a result of this operation, the client should have an available endpoint for
	// software image uploading.
	SetupImageUploadProxy(ctx context.Context, in *SetupImageUploadProxyRequest, opts ...grpc.CallOption) (*SetupImageUploadProxyResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (*DownloadImageResponse, error) {
	out := new(DownloadImageResponse)
	err := c.cc.Invoke(ctx, Admin_DownloadImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SetupImageUploadProxy(ctx context.Context, in *SetupImageUploadProxyRequest, opts ...grpc.CallOption) (*SetupImageUploadProxyResponse, error) {
	out := new(SetupImageUploadProxyResponse)
	err := c.cc.Invoke(ctx, Admin_SetupImageUploadProxy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	// Software Image Management Interface
	//
	// This operation allows downloading and initializing a software image from
	// the specified image repository.
	// Result: As a result of this operation, the requested software image should be present
	// and available for querying via the ETSI NFV IFA-006 Vi-Vnfm API.
	DownloadImage(context.Context, *DownloadImageRequest) (*DownloadImageResponse, error)
	// This operation sets up the software image upload proxy, which can be used for
	// software image uploading from external services.
	// Result: As a result of this operation, the client should have an available endpoint for
	// software image uploading.
	SetupImageUploadProxy(context.Context, *SetupImageUploadProxyRequest) (*SetupImageUploadProxyResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) DownloadImage(context.Context, *DownloadImageRequest) (*DownloadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadImage not implemented")
}
func (UnimplementedAdminServer) SetupImageUploadProxy(context.Context, *SetupImageUploadProxyRequest) (*SetupImageUploadProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupImageUploadProxy not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_DownloadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DownloadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DownloadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DownloadImage(ctx, req.(*DownloadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SetupImageUploadProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupImageUploadProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetupImageUploadProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_SetupImageUploadProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetupImageUploadProxy(ctx, req.(*SetupImageUploadProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.kubevim.kubenfv.api.pb.admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DownloadImage",
			Handler:    _Admin_DownloadImage_Handler,
		},
		{
			MethodName: "SetupImageUploadProxy",
			Handler:    _Admin_SetupImageUploadProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubevim-admin.proto",
}
