// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IptablesEIPLister helps list IptablesEIPs.
// All objects returned here must be treated as read-only.
type IptablesEIPLister interface {
	// List lists all IptablesEIPs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.IptablesEIP, err error)
	// Get retrieves the IptablesEIP from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.IptablesEIP, error)
	IptablesEIPListerExpansion
}

// iptablesEIPLister implements the IptablesEIPLister interface.
type iptablesEIPLister struct {
	listers.ResourceIndexer[*kubeovnv1.IptablesEIP]
}

// NewIptablesEIPLister returns a new IptablesEIPLister.
func NewIptablesEIPLister(indexer cache.Indexer) IptablesEIPLister {
	return &iptablesEIPLister{listers.New[*kubeovnv1.IptablesEIP](indexer, kubeovnv1.Resource("iptableseip"))}
}
