// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/DiMalovanyy/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IptablesSnatRuleLister helps list IptablesSnatRules.
// All objects returned here must be treated as read-only.
type IptablesSnatRuleLister interface {
	// List lists all IptablesSnatRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.IptablesSnatRule, err error)
	// Get retrieves the IptablesSnatRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.IptablesSnatRule, error)
	IptablesSnatRuleListerExpansion
}

// iptablesSnatRuleLister implements the IptablesSnatRuleLister interface.
type iptablesSnatRuleLister struct {
	listers.ResourceIndexer[*kubeovnv1.IptablesSnatRule]
}

// NewIptablesSnatRuleLister returns a new IptablesSnatRuleLister.
func NewIptablesSnatRuleLister(indexer cache.Indexer) IptablesSnatRuleLister {
	return &iptablesSnatRuleLister{listers.New[*kubeovnv1.IptablesSnatRule](indexer, kubeovnv1.Resource("iptablessnatrule"))}
}
