// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OvnDnatRuleLister helps list OvnDnatRules.
// All objects returned here must be treated as read-only.
type OvnDnatRuleLister interface {
	// List lists all OvnDnatRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.OvnDnatRule, err error)
	// Get retrieves the OvnDnatRule from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.OvnDnatRule, error)
	OvnDnatRuleListerExpansion
}

// ovnDnatRuleLister implements the OvnDnatRuleLister interface.
type ovnDnatRuleLister struct {
	listers.ResourceIndexer[*kubeovnv1.OvnDnatRule]
}

// NewOvnDnatRuleLister returns a new OvnDnatRuleLister.
func NewOvnDnatRuleLister(indexer cache.Indexer) OvnDnatRuleLister {
	return &ovnDnatRuleLister{listers.New[*kubeovnv1.OvnDnatRule](indexer, kubeovnv1.Resource("ovndnatrule"))}
}
