// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/DiMalovanyy/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ProviderNetworkLister helps list ProviderNetworks.
// All objects returned here must be treated as read-only.
type ProviderNetworkLister interface {
	// List lists all ProviderNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.ProviderNetwork, err error)
	// Get retrieves the ProviderNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.ProviderNetwork, error)
	ProviderNetworkListerExpansion
}

// providerNetworkLister implements the ProviderNetworkLister interface.
type providerNetworkLister struct {
	listers.ResourceIndexer[*kubeovnv1.ProviderNetwork]
}

// NewProviderNetworkLister returns a new ProviderNetworkLister.
func NewProviderNetworkLister(indexer cache.Indexer) ProviderNetworkLister {
	return &providerNetworkLister{listers.New[*kubeovnv1.ProviderNetwork](indexer, kubeovnv1.Resource("providernetwork"))}
}
