// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/DiMalovanyy/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VlanLister helps list Vlans.
// All objects returned here must be treated as read-only.
type VlanLister interface {
	// List lists all Vlans in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.Vlan, err error)
	// Get retrieves the Vlan from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.Vlan, error)
	VlanListerExpansion
}

// vlanLister implements the VlanLister interface.
type vlanLister struct {
	listers.ResourceIndexer[*kubeovnv1.Vlan]
}

// NewVlanLister returns a new VlanLister.
func NewVlanLister(indexer cache.Indexer) VlanLister {
	return &vlanLister{listers.New[*kubeovnv1.Vlan](indexer, kubeovnv1.Resource("vlan"))}
}
