// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VpcEgressGatewayLister helps list VpcEgressGateways.
// All objects returned here must be treated as read-only.
type VpcEgressGatewayLister interface {
	// List lists all VpcEgressGateways in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcEgressGateway, err error)
	// VpcEgressGateways returns an object that can list and get VpcEgressGateways.
	VpcEgressGateways(namespace string) VpcEgressGatewayNamespaceLister
	VpcEgressGatewayListerExpansion
}

// vpcEgressGatewayLister implements the VpcEgressGatewayLister interface.
type vpcEgressGatewayLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcEgressGateway]
}

// NewVpcEgressGatewayLister returns a new VpcEgressGatewayLister.
func NewVpcEgressGatewayLister(indexer cache.Indexer) VpcEgressGatewayLister {
	return &vpcEgressGatewayLister{listers.New[*kubeovnv1.VpcEgressGateway](indexer, kubeovnv1.Resource("vpcegressgateway"))}
}

// VpcEgressGateways returns an object that can list and get VpcEgressGateways.
func (s *vpcEgressGatewayLister) VpcEgressGateways(namespace string) VpcEgressGatewayNamespaceLister {
	return vpcEgressGatewayNamespaceLister{listers.NewNamespaced[*kubeovnv1.VpcEgressGateway](s.ResourceIndexer, namespace)}
}

// VpcEgressGatewayNamespaceLister helps list and get VpcEgressGateways.
// All objects returned here must be treated as read-only.
type VpcEgressGatewayNamespaceLister interface {
	// List lists all VpcEgressGateways in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcEgressGateway, err error)
	// Get retrieves the VpcEgressGateway from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.VpcEgressGateway, error)
	VpcEgressGatewayNamespaceListerExpansion
}

// vpcEgressGatewayNamespaceLister implements the VpcEgressGatewayNamespaceLister
// interface.
type vpcEgressGatewayNamespaceLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcEgressGateway]
}
