// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NatOutgoingPolicyRuleStatusApplyConfiguration represents a declarative configuration of the NatOutgoingPolicyRuleStatus type for use
// with apply.
type NatOutgoingPolicyRuleStatusApplyConfiguration struct {
	RuleID *string `json:"ruleID,omitempty"`
}

// NatOutgoingPolicyRuleStatusApplyConfiguration constructs a declarative configuration of the NatOutgoingPolicyRuleStatus type for use with
// apply.
func NatOutgoingPolicyRuleStatus() *NatOutgoingPolicyRuleStatusApplyConfiguration {
	return &NatOutgoingPolicyRuleStatusApplyConfiguration{}
}

// WithRuleID sets the RuleID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuleID field is set to the value of the last call.
func (b *NatOutgoingPolicyRuleStatusApplyConfiguration) WithRuleID(value string) *NatOutgoingPolicyRuleStatusApplyConfiguration {
	b.RuleID = &value
	return b
}
