// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NatOutGoingPolicyMatchApplyConfiguration represents a declarative configuration of the NatOutGoingPolicyMatch type for use
// with apply.
type NatOutGoingPolicyMatchApplyConfiguration struct {
	SrcIPs *string `json:"srcIPs,omitempty"`
	DstIPs *string `json:"dstIPs,omitempty"`
}

// NatOutGoingPolicyMatchApplyConfiguration constructs a declarative configuration of the NatOutGoingPolicyMatch type for use with
// apply.
func NatOutGoingPolicyMatch() *NatOutGoingPolicyMatchApplyConfiguration {
	return &NatOutGoingPolicyMatchApplyConfiguration{}
}

// WithSrcIPs sets the SrcIPs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcIPs field is set to the value of the last call.
func (b *NatOutGoingPolicyMatchApplyConfiguration) WithSrcIPs(value string) *NatOutGoingPolicyMatchApplyConfiguration {
	b.SrcIPs = &value
	return b
}

// WithDstIPs sets the DstIPs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstIPs field is set to the value of the last call.
func (b *NatOutGoingPolicyMatchApplyConfiguration) WithDstIPs(value string) *NatOutGoingPolicyMatchApplyConfiguration {
	b.DstIPs = &value
	return b
}
