// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// OvnFipStatusApplyConfiguration represents a declarative configuration of the OvnFipStatus type for use
// with apply.
type OvnFipStatusApplyConfiguration struct {
	Vpc        *string                             `json:"vpc,omitempty"`
	V4Eip      *string                             `json:"v4Eip,omitempty"`
	V6Eip      *string                             `json:"v6Eip,omitempty"`
	V4Ip       *string                             `json:"v4Ip,omitempty"`
	V6Ip       *string                             `json:"v6Ip,omitempty"`
	Ready      *bool                               `json:"ready,omitempty"`
	Conditions []OvnFipConditionApplyConfiguration `json:"conditions,omitempty"`
}

// OvnFipStatusApplyConfiguration constructs a declarative configuration of the OvnFipStatus type for use with
// apply.
func OvnFipStatus() *OvnFipStatusApplyConfiguration {
	return &OvnFipStatusApplyConfiguration{}
}

// WithVpc sets the Vpc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vpc field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithVpc(value string) *OvnFipStatusApplyConfiguration {
	b.Vpc = &value
	return b
}

// WithV4Eip sets the V4Eip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V4Eip field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithV4Eip(value string) *OvnFipStatusApplyConfiguration {
	b.V4Eip = &value
	return b
}

// WithV6Eip sets the V6Eip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V6Eip field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithV6Eip(value string) *OvnFipStatusApplyConfiguration {
	b.V6Eip = &value
	return b
}

// WithV4Ip sets the V4Ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V4Ip field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithV4Ip(value string) *OvnFipStatusApplyConfiguration {
	b.V4Ip = &value
	return b
}

// WithV6Ip sets the V6Ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V6Ip field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithV6Ip(value string) *OvnFipStatusApplyConfiguration {
	b.V6Ip = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *OvnFipStatusApplyConfiguration) WithReady(value bool) *OvnFipStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OvnFipStatusApplyConfiguration) WithConditions(values ...*OvnFipConditionApplyConfiguration) *OvnFipStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
