// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SwitchLBRulePortApplyConfiguration represents a declarative configuration of the SwitchLBRulePort type for use
// with apply.
type SwitchLBRulePortApplyConfiguration struct {
	Name       *string `json:"name,omitempty"`
	Port       *int32  `json:"port,omitempty"`
	TargetPort *int32  `json:"targetPort,omitempty"`
	Protocol   *string `json:"protocol,omitempty"`
}

// SwitchLBRulePortApplyConfiguration constructs a declarative configuration of the SwitchLBRulePort type for use with
// apply.
func SwitchLBRulePort() *SwitchLBRulePortApplyConfiguration {
	return &SwitchLBRulePortApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchLBRulePortApplyConfiguration) WithName(value string) *SwitchLBRulePortApplyConfiguration {
	b.Name = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *SwitchLBRulePortApplyConfiguration) WithPort(value int32) *SwitchLBRulePortApplyConfiguration {
	b.Port = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *SwitchLBRulePortApplyConfiguration) WithTargetPort(value int32) *SwitchLBRulePortApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *SwitchLBRulePortApplyConfiguration) WithProtocol(value string) *SwitchLBRulePortApplyConfiguration {
	b.Protocol = &value
	return b
}
