// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VlanStatusApplyConfiguration represents a declarative configuration of the VlanStatus type for use
// with apply.
type VlanStatusApplyConfiguration struct {
	Subnets    []string                          `json:"subnets,omitempty"`
	Conditions []VlanConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VlanStatusApplyConfiguration constructs a declarative configuration of the VlanStatus type for use with
// apply.
func VlanStatus() *VlanStatusApplyConfiguration {
	return &VlanStatusApplyConfiguration{}
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *VlanStatusApplyConfiguration) WithSubnets(values ...string) *VlanStatusApplyConfiguration {
	for i := range values {
		b.Subnets = append(b.Subnets, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VlanStatusApplyConfiguration) WithConditions(values ...*VlanConditionApplyConfiguration) *VlanStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
