// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/apis/kubeovn/v1"
	applyconfigurationkubeovnv1 "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/applyconfiguration/kubeovn/v1"
	scheme "github.com/kube-nfv/kube-vim-api/kube-ovn-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OvnSnatRulesGetter has a method to return a OvnSnatRuleInterface.
// A group's client should implement this interface.
type OvnSnatRulesGetter interface {
	OvnSnatRules() OvnSnatRuleInterface
}

// OvnSnatRuleInterface has methods to work with OvnSnatRule resources.
type OvnSnatRuleInterface interface {
	Create(ctx context.Context, ovnSnatRule *kubeovnv1.OvnSnatRule, opts metav1.CreateOptions) (*kubeovnv1.OvnSnatRule, error)
	Update(ctx context.Context, ovnSnatRule *kubeovnv1.OvnSnatRule, opts metav1.UpdateOptions) (*kubeovnv1.OvnSnatRule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ovnSnatRule *kubeovnv1.OvnSnatRule, opts metav1.UpdateOptions) (*kubeovnv1.OvnSnatRule, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubeovnv1.OvnSnatRule, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubeovnv1.OvnSnatRuleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubeovnv1.OvnSnatRule, err error)
	Apply(ctx context.Context, ovnSnatRule *applyconfigurationkubeovnv1.OvnSnatRuleApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.OvnSnatRule, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, ovnSnatRule *applyconfigurationkubeovnv1.OvnSnatRuleApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.OvnSnatRule, err error)
	OvnSnatRuleExpansion
}

// ovnSnatRules implements OvnSnatRuleInterface
type ovnSnatRules struct {
	*gentype.ClientWithListAndApply[*kubeovnv1.OvnSnatRule, *kubeovnv1.OvnSnatRuleList, *applyconfigurationkubeovnv1.OvnSnatRuleApplyConfiguration]
}

// newOvnSnatRules returns a OvnSnatRules
func newOvnSnatRules(c *KubeovnV1Client) *ovnSnatRules {
	return &ovnSnatRules{
		gentype.NewClientWithListAndApply[*kubeovnv1.OvnSnatRule, *kubeovnv1.OvnSnatRuleList, *applyconfigurationkubeovnv1.OvnSnatRuleApplyConfiguration](
			"ovn-snat-rules",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kubeovnv1.OvnSnatRule { return &kubeovnv1.OvnSnatRule{} },
			func() *kubeovnv1.OvnSnatRuleList { return &kubeovnv1.OvnSnatRuleList{} },
		),
	}
}
